// src/components/qwik/ThemeController.tsx
import { component$, useSignal, useTask$ } from "@builder.io/qwik";

const ThemeController = component$(() => {
  const isDark = useSignal(
    JSON.parse(localStorage.getItem("isdark") as string),
  );

  useTask$(({ track }) => {
    track(() => isDark.value);
    localStorage.setItem("isdark", JSON.stringify(isDark.value));
  });

  return (
    <li>
      <div class="justify-between">
        <div class="text-text">Theme</div>
        <label class="cursor-pointer grid place-items-center">
          <input
            type="checkbox"
            value="dark"
            checked={isDark.value}
            // @ts-ignore
            onChange$={() => (isDark.value = !isDark.value)}
            class="toggle theme-controller bg-base-content row-start-1 col-start-1 col-span-2"
          />
          <svg
            class="col-start-1 row-start-1 stroke-base-100 fill-base-100"
            xmlns="http://www.w3.org/2000/svg"
            width="14"
            height="14"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <circle cx="12" cy="12" r="5"></circle>
            <path d="M12 1v2M12 21v2M4.2 4.2l1.4 1.4M18.4 18.4l1.4 1.4M1 12h2M21 12h2M4.2 19.8l1.4-1.4M18.4 5.6l1.4-1.4"></path>
          </svg>
          <svg
            class="col-start-2 row-start-1 stroke-base-100 fill-base-100"
            xmlns="http://www.w3.org/2000/svg"
            width="14"
            height="14"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path>
          </svg>
        </label>
      </div>
    </li>
  );
});

export default ThemeController;

// src/components/svelte/ThemeController.svelte
<script lang="ts">
let isDark = JSON.parse(<string>localStorage.getItem("isdark"))
$: JSON.stringify(localStorage.setItem("isdark", isDark))
</script>

<li>
    <div class="justify-between">
        <div class="text-text">Theme</div>
        <label class="cursor-pointer grid place-items-center">
            <input
                    type="checkbox"
                    value="dark"
                    class="toggle theme-controller bg-base-content row-start-1 col-start-1 col-span-2"
            />
            <svg
                    class="col-start-1 row-start-1 stroke-base-100 fill-base-100"
                    xmlns="http://www.w3.org/2000/svg"
                    width="14"
                    height="14"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
            >
                <circle cx="12" cy="12" r="5"></circle>
                <path
                        d="M12 1v2M12 21v2M4.2 4.2l1.4 1.4M18.4 18.4l1.4 1.4M1 12h2M21 12h2M4.2 19.8l1.4-1.4M18.4 5.6l1.4-1.4"
                ></path>
            </svg>
            <svg
                    class="col-start-2 row-start-1 stroke-base-100 fill-base-100"
                    xmlns="http://www.w3.org/2000/svg"
                    width="14"
                    height="14"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
            >
                <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path>
            </svg>
        </label>
    </div>
</li>
